name: daily-devcard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1,3,5'

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        with:
          user_id: ${{ secrets.USER_ID }}
